### ISSUE TITLE
Can't launch..wayland issue ?

### ISSUE THREAD

**Issue by Pommede** [Neverous/efibooteditor#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi
i tried to launch efibooteditor but it close immediately..i installed qt5-wayland and qt6-wayland..same issue :-(
i've got this message whan i use a term
_qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
qt.core.qobject.connect: QObject::disconnect: Unexpected nullptr parameter
/usr/include/c++/13.2.1/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'efibooteditor' terminated by signal SIGABRT (Abandon)_

an idea ?
thks

### Environment

- Application version:efibooteditor
- Operating system:garuda linux
- EFI/BIOS/Motherboard vendor:
- EFI/BIOS version:

**Comment by Neverous** [comment]
I think its unrelated to Qt, they don't use STL underneath AFAIK as they have their own implementations. Its probably bug in the app code - I'd guess with regards to parsing the EFI entries, some edge case or entry I haven't encountered yet.

 Can you try `efibooteditor --dump raw.json` in the terminal and share the `raw.json` with me?

Other option would be to get debug build and run it with gdb it should show exactly where it crashes.

**Comment by Pommede** [comment]
Thks for your response !
it's a bit too "technical" for me :-) but here's the json
[raw.json](https://github.com/Neverous/efibooteditor/files/14000658/raw.json)

**Comment by Neverous** [comment]
Yeah, not related to GUI - the messages apart from last assertion failed are just warnings from the GUI toolkit.
Bug in the code, thanks to your dump it was easy to find. 
Should be fixed in next release. Or you can build from HEAD / download one of the newest builds from [latest](https://github.com/Neverous/efibooteditor/releases/tag/latest) / build from git version of package in [AUR](https://aur.archlinux.org/pkgbase/efibooteditor-git)

**Comment by Pommede** [comment]
ok thks, i'll wait the next release i think ;-)
too beginner to build it...
