### ISSUE TITLE
"Error saving Timeout" when trying to save 

### ISSUE THREAD

**Issue by Lennart1978** [Neverous/efibooteditor#218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on File/Save to write the edited bootoptions, I always get the error message :"Error saving Timeout" (no matter how many seconds I select for timeout)
Error trace:
efivarfs.c:264 efivarfs_get_variable(): : open(/sys/firmware/efi/efivars/DriverOrder-8be4df61-93ca-11d2-aa0d-00e098032b8c)

### Environment

- Application version: 1.4.0-aur.1
- Operating system: Archlinux (up to date 15.05.24)
- EFI/BIOS/Motherboard vendor: Asrock A520M-itx
- EFI/BIOS version: L3.44[Beta]

### Raw EFI data

{
    "Boot": {
        "0000": {
            "efi_attributes": 7,
            "raw_data": "AAAAAHQATABpAG4AdQB4ACAAQgBvAG8AdAAgAE0AYQBuAGEAZwBlAHIAAAAEASoAAQAAAAAIAAAAAAAAAAAQAAAAAAD4SB/vgg8kSaMfv3nYvEx7AgIEBEYAXABFAEYASQBcAFMAWQBTAFQARQBNAEQAXABTAFkAUwBUAEUATQBEAC0AQgBPAE8AVABYADYANAAuAEUARgBJAAAAf/8EAA=="
        },
        "0001": {
            "efi_attributes": 7,
            "raw_data": "AAAAAF4AVQBFAEYASQAgAE8AUwAAAAQBKgABAAAAAAgAAAAAAAAAABAAAAAAAPhIH++CDyRJox+/edi8THsCAgQEMABcAEUARgBJAFwAQgBPAE8AVABcAEIATwBPAFQAWAA2ADQALgBFAEYASQAAAH//BAAAAEJP"
        },
        "0002": {
            "efi_attributes": 7,
            "raw_data": "AQAAAFAAQQBSAEMASABMAEkATgBVAFgAIABFAEYASQAgAFMAVABVAEIAAAAEASoAAQAAAAAIAAAAAAAAAAAQAAAAAAD4SB/vgg8kSaMfv3nYvEx7AgIEBCIAXABWAE0ATABJAE4AVQBaAC0ATABJAE4AVQBYAAAAf/8EAHIAbwBvAHQAPQBVAFUASQBEAD0AYQAyAGUAZQAxAGIANQBjAC0AZQBkADAANAAtADQAZQAyADAALQA4ADYAZQBkAC0ANwA1ADMAZgA4AGUAOAA3AGMAZQA3ADgAIAByAHcAIAByAG8AbwB0AGYAcwB0AHkAcABlAD0AZQB4AHQANAAgAHEAdQBpAGUAdAAgAGkAbgBpAHQAcgBkAD0AXABpAG4AaQB0AHIAYQBtAGYAcwAtAGwAaQBuAHUAeAAuAGkAbQBnACAAaABvAHMAdABuAGEAbQBlAD0ATABFAE4ATgBBAFIAVAB6ACAAbgBvAGgAaQBiAGUAcgBuAGEAdABlACAAbgBvAHIAZQBzAHUAbQBlACAAdgBtAF8AZABlAGIAdQBnAD0ALQA="
        }
    },
    "BootCurrent": {
        "efi_attributes": 6,
        "raw_data": "AgA="
    },
    "BootOptionSupport": {
        "efi_attributes": 6,
        "raw_data": "EwMAAA=="
    },
    "BootOrder": {
        "efi_attributes": 7,
        "raw_data": "AgAAAAEA"
    },
    "OsIndications": {
        "efi_attributes": 7,
        "raw_data": "AAAAAAAAAAA="
    },
    "OsIndicationsSupported": {
        "efi_attributes": 6,
        "raw_data": "AwAAAAAAAAA="
    },
    "SecureBoot": {
        "efi_attributes": 6,
        "raw_data": "AA=="
    },
    "SetupMode": {
        "efi_attributes": 6,
        "raw_data": "AQ=="
    },
    "Timeout": {
        "efi_attributes": 7,
        "raw_data": "AAA="
    },
    "VendorKeys": {
        "efi_attributes": 6,
        "raw_data": "AQ=="
    },
    "_Type": "raw"
}

### Additional information

lennart@LENNARTz:~$ efibootmgr
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0000,0001
Boot0000  Linux Boot Manager	HD(1,GPT,ef1f48f8-0f82-4924-a31f-bf79d8bc4c7b,0x800,0x100000)/\EFI\SYSTEMD\SYSTEMD-BOOTX64.EFI
Boot0001  UEFI OS	HD(1,GPT,ef1f48f8-0f82-4924-a31f-bf79d8bc4c7b,0x800,0x100000)/\EFI\BOOT\BOOTX64.EFI0000424f
Boot0002* ARCHLINUX EFI STUB	HD(1,GPT,ef1f48f8-0f82-4924-a31f-bf79d8bc4c7b,0x800,0x100000)/\VMLINUZ-LINUX72006f006f0074003d0055005500490044003d00610032006500650031006200350063002d0065006400300034002d0034006500320030002d0038003600650064002d00370035003300660038006500380037006300650037003800200072007700200072006f006f0074006600730074007900700065003d006500780074003400200071007500690065007400200069006e0069007400720064003d005c0069006e0069007400720061006d00660073002d006c0069006e00750078002e0069006d006700200068006f00730074006e0061006d0065003d004c0045004e004e004100520054007a0020006e006f00680069006200650072006e0061007400650020006e006f0072006500730075006d006500200076006d005f00640065006200750067003d002d00

### Steps to reproduce

1. Edit Bootoptions
2. Click 'File->Save'
3. Get error message "Error saving Timeout"
4. Beeing sad ;-)

**Comment by Neverous** [comment]
Interestingly the error stack trace is broken as it mentions `DriverOrder` not the `Timeout` (and also `get_variable` not `set_variable` like there was actually no error around the `Timeout` saving :confused: ). And on a quick glance I don't see anything wrong around saving `Timeout` in the code (and works fine on my side) and there are other entries saved before that so presumably it worked fine, it might require bit more digging :thinking: 

Have you tried changing the `Timeout` setting with efibootmgr to see if that works? `efibootmgr -t SECONDS` ?

**Comment by Lennart1978** [comment]
I don't know why, but I can not change the Timeout with "sudo efibootmgr -t 3" for example.
I always get: "permission denied !". I changed the rights for my EFI partition, added the Kernel paramater "efi_no_storage_paranoia" - but no success. Always "permission denied !".
Then I changed the Timeout from 0 to 3 in the UEFI Firmware setup of my mainboard. After that "efibootmgr" shows the timeout is 3 seconds now. I started to use the efibooteditor, deleted one entry and changed the description of one. Again I clicked on save and got the known "Error saving Timeout" message. BUT it saved my changes now ! I closed the efibooteditor, opened it again and voila it shows the entries with all my changes I have done. Also efibootmgr shows the changes.
---> It seems to work now despite the error message.

**Comment by Neverous** [comment]
If efibootmgr has the same issue then it seems the problems lies in the BIOS blocking access to changing the `Timeout` for some reason (or maybe in efivar or linux kernel itself, though not sure why those would have anything special for `Timeout` while other vars work fine). Maybe there is some security lock option in the UEFI Firmware setup?
Might be worth rechecking later after you update out of beta BIOS as well, maybe it's just some weird bug on their side.

Not much I can do about it :disappointed: Well apart from fixing the error stack trace so it also shows the `permission denied` from `set_variable`  in there instead of whatever its grabbing right now cause that's some weird bug on my side.


> It seems to work now despite the error message.

The boot entries are saved before `Timeout` saving is attempted, so that should have worked before as well. I might try to add some logic to check if variable has exactly the same value before attempting to overwrite it, that would workaround this issue at least when you're not actually changing the value of the `Timeout` (as right now all boot settings are overwritten on save, even if they are exactly the same) :thinking:

// maybe related:
- https://github.com/rhboot/efibootmgr/issues/19
- https://github.com/rhboot/efivar/issues/95

**Comment by Lennart1978** [comment]
I'll change the bios version and see what happens. Otherwise the program works perfectly and it is the best program I know of for manipulating EFI boot options. Thank you for your attention and effort.
