### ISSUE TITLE
Cannot read custom vendor Key#### entries

### ISSUE THREAD

**Issue by hoegge** [Neverous/efibooteditor#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I run latest version I get the error:
![image](https://github.com/user-attachments/assets/55229e53-7a3c-4028-a695-fd949a2b213f)

Failed to load some EFI Boot Manager entries:

  - Key0001: failed deserialization
  - Key0002: failed deserialization
  - Key0008: failed deserialization
  - Key0009: failed deserialization
  - Key0004: failed deserialization

### Environment

- Application version:  Version 1.5.0
- Operating system: Windows 10 Pro
- EFI/BIOS/Motherboard vendor: Lenovo
- EFI/BIOS version: N3BET61W 1.39
- 
![image](https://github.com/user-attachments/assets/1977f664-a650-41e1-b47d-10216de01075)

### Raw EFI data

[efi.data.json](https://github.com/user-attachments/files/16887131/efi.data.json)

### Steps to reproduce

1. Open EFI Boot Editor

**Comment by Neverous** [comment]
Checking the `Key*` entries in your dump, it seems the BIOS on this device stores some additional data in them (like on-screen message? `Launching the Startup Interrupt Menu`) that's not really supported by the standard (and I cant find any documentation on their additions anywhere).

I don't think I can do much about it, they are broken entries :thinking: (at least not valid to the UEFI specification) 
I think the best I could do is ignore that additional data and hope it will be fine without it if you save :thinking:

**Comment by Neverous** [comment]
This should be "fixed" (worked around really), since 1.5.1. Feel free to reopen if otherwise.
