### ISSUE TITLE
Which version to use.

### ISSUE THREAD

**Issue by harryray33** [Neverous/efibooteditor#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Which version for Windows 11

### Additional information

I have a new Windows 11 system...I'm not sure which version to download.

Thanks.

**Comment by Neverous** [comment]
None are really guaranteed to work (see [INSTALL](https://github.com/Neverous/efibooteditor/blob/master/INSTALL.md#pre-built-packages)), best to build from source but I would try `*-windows-2022-qt-6.*-MSVC.msi` - this one is also published to [winget](https://github.com/Neverous/efibooteditor/blob/master/INSTALL.md#winget)
