### ISSUE TITLE
Qt5.9 compatibility

### ISSUE THREAD

**Issue by zensubz** [Neverous/efibooteditor#34]
Not reporting any bug, but wanted to make a request.

Will it be possible to make this app compatible with Qt 5.9.7, as it is the only version that is available in my Linux OS.

**Comment by Neverous** [comment]
I'm not interested in that myself as Qt 5.9 is long time unsupported (and wasn't even LTS) but if anyone want's to try and make necessary fixes while not breaking anything in recent Qt versions you're welcome to try.
