### ISSUE TITLE
Use system FindZLIB

### ISSUE THREAD

**Issue by uis246** [Neverous/efibooteditor#348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cmake errors on bundled FindZLIB and says policy CMP0159 is not known.
Cmake 3.28.

### Environment

- Application version:
- Operating system:
- EFI/BIOS/Motherboard vendor:
- EFI/BIOS version:

**Comment by zinin** [comment]
have same error on 1.5.0 and 1.5.1

**Comment by Neverous** [comment]
Should be fixed in [1.5.2](https://github.com/Neverous/efibooteditor/releases/tag/v1.5.2)
