### ISSUE TITLE
"Error removing old entries!"

### ISSUE THREAD

**Issue by Skalt711** [Neverous/efibooteditor#46]
Unfortunately, the title error appears with the context: "Error trace:
windows.h:-1 SetFirmwareEnvironmentVariableEx(): Unknown error: Параметр задан неверно."

The app is able to duplicate existing entries, but it can't delete or even modify them. I can tell that other EFI managers work fine, such as efibootmgr under Linux, bcdedit under Windows via fwbootmgr and EasyUEFI under Windows.

Is it possible to solve this issue?

**Comment by Neverous** [comment]
Works fine for me, it must be something either with the values you're trying to set or maybe your firmware doesn't like some flag that we're setting by default :thinking: 
Also you mentioned efibootmgr on Linux, can you try this on Linux?

What do you mean by `The app is able to duplicate existing entries`? There is no duplicate entry function :thinking: You can create a new entry, set the same values as some other one and it saves fine, but if you change something it doesn't? If so then the issue must be in the differences you're making, can you share before and after? (`File -> Export` saves whats visible in the GUI).

Though the deletes should work just fine no matter what as they take no input :thinking: 

- Can you share OS version, efibooteditor version, EFI/BIOS vendor?
- Raw dump might also show something (`Help -> Dump raw EFI data`), can you share it?

**Comment by ylmw0131** [comment]
I got same error on my Windows 10

**Comment by Neverous** [comment]
I think I fixed this with https://github.com/Neverous/efibooteditor/pull/98, can you try latest build from https://github.com/Neverous/efibooteditor/releases/tag/latest ?

**Comment by manutortosa** [comment]
> I think I fixed this with #98, can you try latest build from https://github.com/Neverous/efibooteditor/releases/tag/latest ?

i had de same issue and seems to be fixed

**Comment by Neverous** [comment]
Awesome, thank you. Closing this then. Feel free to reopen in case it resurfaces.
