### ISSUE TITLE
Improve translation support

### ISSUE THREAD

**Issue by bovirus** [Neverous/efibooteditor#63]
@Neverous 

I'd like to make the Italian language for your software.

Could be possible to create the English master 

https://github.com/Neverous/efibooteditor/blob/master/translations/efibooteditor_en.ts

without location reference?

This location references can change in many block between versions and if you want find differences between different language  version is quite complex to find the real difference if there are many changes about locations.

Thanks.

**Comment by Neverous** [comment]
I'm not sure, I just use builtin functions to generate them automatically and I would think the additional references might actually be helpful sometimes in figuring out whats what :thinking: (and I assume it's the default for some reason, also when I open it in qt linguist, it has nice visualization this way :stuck_out_tongue_winking_eye: )

For diffing and other manual checks you can always `grep -v location efibooteditor_en.ts` if you don't need them :thinking:

**Comment by Neverous** [comment]
Also not sure if that helps or not but I just set up project on [Weblate](https://hosted.weblate.org/projects/efibooteditor/efibooteditor/)

**Comment by bovirus** [comment]
@Neverous 

Thanks.
Translation complete

object(raw_data: string, efi_attributes: number)
boot-args

can be translated?

**Comment by bovirus** [comment]
@Neverous 

Please add in github home page info about translations and reference to Weblate.

**Comment by bovirus** [comment]
@Neverous 

Now that I can complete the Italian translation how can test it in place?

Is there a way to put the .qm file (compiled of .ts) or run the application with a command line to load new Italian language file?

**Comment by bovirus** [comment]
@Neverous 

Now that I can complete the Italian translation how can test it in place?

Is there a way to put the .qm file (compiled of .ts) or run the application with a command line to load new Italian language file?

**Comment by bovirus** [comment]
@Neverous 

Now that I can complete the Italian translation how can test it in place?
Is there a way to put the .qm file (compield of .ts) or run the application with a command line to laod new italian language file?

Found!
Copy in translation folder the file **efibooteditor_it.qm**

**Comment by Neverous** [comment]
> Thanks. Italian translation complete

Awesome. Thank you!

> Please confirm is these strings can be translated
> 
> object(raw_data: string, efi_attributes: number)
> boot-args

Partially. The first one is just an expected JSON structure description in error message so `object`, `string` and `number` should be fine to translate I think (`raw_data` and `efi_attributes` are field names in JSON file). 

`boot-args` is a name of the [EFI variable](https://support.apple.com/en-us/HT202528) used by macOS so probably not, I don't think they're naming it nicely anywhere :thinking: 

I'll try adding these as a comments so it shows up in the translation file.

> Consider to set Weblate project not as trial project but as final project.

Yeah, I've set it up yesterday. It's awaiting confirmation from their side.

> Please set project to accept translated strings that are equal to original strings.

Adjusted the flags :+1:

**Comment by bovirus** [comment]
@Neverous 

Please remind to add these strings

https://github.com/Neverous/efibooteditor/issues/67

**Comment by Neverous** [comment]
I'll close this as finished once/if Weblate accepts the project. Unless there is anything else you'd like to see adjusted. Let me know.
