### ISSUE TITLE
GUI issues - Untranslated strings

### ISSUE THREAD

**Issue by bovirus** [Neverous/efibooteditor#67]
@Neverous 

Please check screenshot about GUI issues (untranslated strings and GUI request for chganges):

![EFI Boot Edit 1 2 0 - GUI - 01](https://user-images.githubusercontent.com/1262554/232479907-81fca63e-a378-4765-adaa-bfa52217c712.jpg)
Untranslated string.
Please add it to language file.

![EFI Boot Edit 1 2 0 - GUI - 02](https://user-images.githubusercontent.com/1262554/232479913-cef23fef-bfa6-4b4c-bcfe-b6da405962cd.jpg)
Untranslated strings.
Please add them to language file.
Please add before version number the string "Version" (that could be translated).

![EFI Boot Edit 1 2 0 - GUI - 03](https://user-images.githubusercontent.com/1262554/232479914-d7b962c7-cf61-4a82-826c-741a28e6d3c4.jpg)
Please move the strings in red box on the right to use space not used and avoid overlap with string (Functions:)

![EFI Boot Edit 1 2 0 - GUI - 04](https://user-images.githubusercontent.com/1262554/232479915-1021a06b-9e7b-4ba0-998d-296a46a1b4ef.jpg)
The string "Optional" and relative box value are not aligned vertically.

**Comment by Neverous** [comment]
`Searching EFI Boot Manager entries...` should already be in the translation files :thinking: 
Reorganized About dialog a bit, version and description blocks should now be translatable. (`Website` also is already there)

As for the UI adjustments, the `Optional` label should be aligned to top, it is for me (but Ill try to see what Windows is doing and if there is a way to adjust it there if the top alignment isnt actually working).

And the features block, I'm not sure about aligning it to the right it then goes off completely if you fullscreen the app. And the strings also shouldn't overlap there is a margin between them, though I might increase it a bit :thinking:

**Comment by bovirus** [comment]
@Neverous 

I updated the strings in Weblate.

Could you please consider when make some change to the source code to product a nightly build that contains all new changes?

Thanks.

**Comment by Neverous** [comment]
> Could you please consider when make some change to the source code to product a nightly build that contains all new changes?

I already setup building on each commit to master but I see now the artifacts are not publicly available for download. Ill try adding some pre-releases or something so anyone can download them :+1:  Created new task for that https://github.com/Neverous/efibooteditor/issues/69.

> How can compile your source?

Build instructions are available in https://github.com/Neverous/efibooteditor/blob/master/INSTALL.md

**Comment by Neverous** [comment]
I believe this is done then. Feel free to reopen if I missed any more strings :wink:
