### ISSUE TITLE
Testing translations

### ISSUE THREAD

**Issue by Rudolfin** [Neverous/efibooteditor#71]
Today I translated efibooteditor into Slovak via the WEBLATE translation server. How do I implement it when efibooteditor doesn't have a language changer available? I am using EFIBootEditor-v1.2.1-windows-2022-qt-6.5.0-MSVC.msi installation.
Thanks for the reply.

**Comment by Rudolfin** [comment]
I downloaded the file efibooteditor_sk.ts and implemented it in the QT editor as efibooteditor_sk.qm and saved it in the \translations folder.
What else should I do?

**Comment by Neverous** [comment]
It should follow your system language. I'm not sure if there is a way to set language per app on Windows if you're not using Slovak globally :thinking: (on Linux you can run `LC_ALL=sk efibooteditor` maybe similar work on Windows from terminal?)

Or if you meant how to install the language without [building](https://github.com/Neverous/efibooteditor/blob/master/INSTALL.md) the whole application yourself from source, I believe you need to use [lrelease](https://doc.qt.io/qt-6/linguist-lrelease.html) to compile the resulting Slovak `.ts` file into `.qm` one and then put it in `translations` directory in the application folder (alongside the `efibooteditor.exe`) and it should pick it up automatically.

**Comment by Rudolfin** [comment]
Everything is OK now. My mistake was that I used the installation file EFIBootEditor-v1.2.1-windows-2022-qt-6.5.0-MSVC.msi, which does not contain the "translations" folder.
Therefore, I didn't know how to use the efibooteditor_en.qm language file. Then I used the installation file EFIBootEditor-v1.2.1-windows-2022-qt-6.2.4-MSVC.zip, which contains the "translations" folder. My translation work was not in vain. 😊
Rudolfin

**Comment by Rudolfin** [comment]
Everything is OK now. My mistake was that I used the installation file EFIBootEditor-v1.2.1-windows-2022-qt-6.5.0-MSVC.msi, which does not contain the "translations" folder.Therefore, I didn't know how to use the efibooteditor_sk.qm language file. Then I used the installation file EFIBootEditor-v1.2.1-windows-2022-qt-6.2.4-MSVC.zip, which contains the "translations" folder. My translation work was not in vain. 😊Rudolfin Odoslané z aplikácie Pošta pre Windows Od: Maciej SzeptuchOdoslané: nedeľa 23. apríla 2023 23:17Komu: Neverous/efibooteditorKópia: Rudolfin; AuthorPredmet: Re: [Neverous/efibooteditor] Slovak language (Issue #71) It should follow your system language. I'm not sure if there is a way to set language per app on Windows if you're not using Slovak globally 🤔 (on Linux you can run LC_ALL=sk efibooteditor maybe similar work on Windows from terminal?)Or if you meant how to install the language without building the whole application yourself from source, I believe you need to use lrelease to compile the resulting Slovak .ts file into .qm one and then put it in translations directory in the application folder (alongside the efibooteditor.exe) and it should pick it up automatically.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Neverous** [comment]
Ah, yes the Qt 6.5.0 has a [bug](https://codereview.qt-project.org/c/qt/qtbase/+/468903) in windows release tool and the base translations aren't included there because of that. But you could've created the `translations` folder manually and it should've worked and pick up your file. This should be fixed in release with Qt 6.5.1+ and the translations folder will probably reappear then.

Anyway closing it then. Feel free to reopen if needed.
