### ISSUE TITLE
Manual and some problems with multi EFI choice screens.

### ISSUE THREAD

**Issue by MrTatiTunes** [Neverous/efibooteditor#81]
I have such a strange issue:
https://www.youtube.com/watch?v=zKA_cRkyosM
it behaves this way both in CSM and EFI

Please instruct me what to do?
Instruct me HOW TO READ IT and Edit

From BCD Edit in system admin CMD:
***:\Users\**\Desktop>bcdedit /enum firmware

Firmware Boot Manager
---------------------
identifier              {fwbootmgr}
displayorder            {355b2e79-0094-11ee-9619-806e6f6e6963}
                        {bootmgr}
                        {355b2e7d-0094-11ee-9619-806e6f6e6963}
                        {355b2e86-0094-11ee-9619-806e6f6e6963}
timeout                 2

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=M:
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {09f90827-004c-11ee-994c-806e6f6e6963}
displayorder            {c46fb3fd-fce2-11ed-993e-806e6f6e6963}
                        {current}
                        {15a4a817-fcb9-11ed-9939-98ad65447797}
                        {a22d34ce-f59a-11ed-8461-fc52d37a8085}
                        {a22d34cd-f59a-11ed-8461-fc52d37a8085}
                        {dc155795-fec6-11ed-9948-182649ce2907}
                        {ab364197-0047-11ee-994b-182649ce2907}
toolsdisplayorder       {memdiag}
timeout                 10
displaybootmenu         Yes

Firmware Application (101fffff)
-------------------------------
identifier              {355b2e79-0094-11ee-9619-806e6f6e6963}
device                  partition=E:
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager

Firmware Application (101fffff)
-------------------------------
identifier              {355b2e7d-0094-11ee-9619-806e6f6e6963}
device                  partition=O:
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager

Firmware Application (101fffff)
-------------------------------
identifier              {355b2e86-0094-11ee-9619-806e6f6e6963}
device                  partition=Q:
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager

bcdedit /enum 👍 

**:\Users\*******\Desktop>bcdedit /enum

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=M:
path                    \EFI\MICROSOFT\BOOT\BOOTMGFW.EFI
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {09f90827-004c-11ee-994c-806e6f6e6963}
displayorder            {c46fb3fd-fce2-11ed-993e-806e6f6e6963}
                        {current}
                        {15a4a817-fcb9-11ed-9939-98ad65447797}
                        {a22d34ce-f59a-11ed-8461-fc52d37a8085}
                        {a22d34cd-f59a-11ed-8461-fc52d37a8085}
                        {dc155795-fec6-11ed-9948-182649ce2907}
                        {ab364197-0047-11ee-994b-182649ce2907}
toolsdisplayorder       {memdiag}
timeout                 10
displaybootmenu         Yes

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=***:
path                    \WINDOWS\system32\winload.efi
description             NVMe-LTSC-Z-OK-on-F
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {15a4a812-fcb9-11ed-9939-98ad65447797}
displaymessageoverride  Recovery
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=Z:
systemroot              \WINDOWS
resumeobject            {09f90827-004c-11ee-994c-806e6f6e6963}
nx                      OptIn
bootmenupolicy          Standard

Windows Boot Loader
-------------------
identifier              {15a4a817-fcb9-11ed-9939-98ad65447797}
device                  partition=E:
path                    \Windows\system32\winload.efi
description             NVMe-Win10-Z-OK-on E
locale                  en-US
inherit                 {bootloadersettings}
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=E:
systemroot              \Windows
resumeobject            {25bde4a3-0050-11ee-93f7-806e6f6e6963}
nx                      OptIn
bootmenupolicy          Standard

Windows Boot Loader
-------------------
identifier              {a22d34ce-f59a-11ed-8461-fc52d37a8085}
device                  unknown
path                    \Windows\system32\winload.efi
description             NVMe-Win7-Z-500-on-R
locale                  en-US
loadoptions             DDISABLE_INTEGRITY_CHECKS
osdevice                unknown
systemroot              \Windows
resumeobject            {17b5cfe2-f762-11ed-8d67-806e6f6e6963}
bootmenupolicy          Standard

Windows Boot Loader
-------------------
identifier              {a22d34cd-f59a-11ed-8461-fc52d37a8085}
device                  partition=S:
path                    \Windows\system32\winload.efi
description             WIN-7-Temp-1000 S
locale                  en-US
osdevice                partition=S:
systemroot              \Windows
bootmenupolicy          Standard

Windows Boot Loader
-------------------
identifier              {dc155795-fec6-11ed-9948-182649ce2907}
device                  partition=***:
path                    \Windows\system32\winload.efi
description             OK Note Samsung EFI
locale                  en-US
osdevice                partition=***:
systemroot              \Windows

Windows Boot Loader
-------------------
identifier              {ab364197-0047-11ee-994b-182649ce2907}
device                  ramdisk=[O:]\boot\macrium\WinREFiles\media\sources\boot.wim,{ramdiskoptions}
path                    \windows\system32\boot\winload.efi
description             Macrium Reflect System Recovery
osdevice                ramdisk=[O:]\boot\macrium\WinREFiles\media\sources\boot.wim,{ramdiskoptions}
systemroot              \Windows
detecthal               Yes
winpe                   Yes

and this what show EFIBOOTEDITOR
:
![obraz](https://github.com/Neverous/efibooteditor/assets/30302908/fd1e33f5-30aa-44e1-9b96-e0196ae5d2cf)
(BTW, how to change language? Edit ini or what?)

**Comment by Neverous** [comment]
So I assume you want to get to a state where only single Windows Boot Manager exists and it boots single Windows installation?

All screens shown in the video are from **Windows Boot Manager** not **UEFI Boot Manager** - EFIBootEditor has no saying into its config unfortunately - as far as I know it's stored somewhere on boot drive in registry files, not in EFI variables :disappointed: EFIBootManager only shows the entrypoints Windows Boot Manager installed for itself in firmware.

I think you can edit those windows boot entries with the [BCDEdit](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-boot-entries) you already used to print them, in GUI maybe with [msconfig](https://answers.microsoft.com/en-us/windows/forum/all/msconfig-the-system-configuration-tool/273dea8e-4cbe-47e9-8489-f400e879ce17) (they should show up in the Boot tab I think)?

![msconfig](https://github.com/Neverous/efibooteditor/assets/765629/f7689177-a95d-4342-92c1-7ece66ec3eb4)


As for the language, it should follow the system language. There is no dedicated language switcher currently.

**Comment by MrTatiTunes** [comment]
> So I assume you want to get to a state where only single Windows Boot Manager exists and it boots single Windows installation?
> 
> All screens shown in the video are from **Windows Boot Manager** not **UEFI Boot Manager** - EFIBootEditor has no saying into its config unfortunately - as far as I know it's stored somewhere on boot drive in registry files, not in EFI variables 😞 EFIBootManager only shows the entrypoints Windows Boot Manager installed for itself in firmware.
> 
> I think you can edit those windows boot entries with the [BCDEdit](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/adding-boot-entries) you already used to print them, in GUI maybe with [msconfig](https://answers.microsoft.com/en-us/windows/forum/all/msconfig-the-system-configuration-tool/273dea8e-4cbe-47e9-8489-f400e879ce17) (they should show up in the Boot tab I think)?
> 
> ![msconfig](https://user-images.githubusercontent.com/765629/242940264-f7689177-a95d-4342-92c1-7ece66ec3eb4.png)
> 
> As for the language, it should follow the system language. There is no dedicated language switcher currently.

Rather not, I would like to have One screen of choice and one set of option with possibility to load WinPe for at least one system or recovery for the same.

Trying to figure out implementations of UEFI 7 (UefiSeven), GOP, but explanations are always missing one "turn" on the way. Or do not designate the partition, the disk or whatever they call in instruction precisely. I have already multi disk multi system working OK, but switching off UEFI for Win 7 is a bit odd,
This system was working on my previous PC with full UEFI, and wondering if just a clone of 3 first partitions would restore Win 7 to normal uefi start?

**Comment by MrTatiTunes** [comment]
So far so good, I have removed one HDD with GPT and one screen vanished, the one with all odd options. I was sure UEFI is reading something from NVRM or somewhere else, or only from designated disk sources.
