### ISSUE TITLE
/usr/bin/ld: cannot find -lefiboot: No such file or directory

### ISSUE THREAD

**Issue by Moji14** [Neverous/efibooteditor#82]
I got this error:

[ 96%] Building CXX object CMakeFiles/efibooteditor.dir/qrc_translations.cpp.o
[100%] Linking CXX executable efibooteditor
/usr/bin/ld: cannot find -lefiboot: No such file or directory
/usr/bin/ld: cannot find -lefivar: No such file or directory
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/efibooteditor.dir/build.make:448: efibooteditor] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/efibooteditor.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

**Comment by Moji14** [comment]
This is mi platform configuration:

Linux R2D2 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
qtcreator (6.0.2-2build1).
qtbase5-dev (5.15.3+dfsg-2ubuntu0.2).
qt5-qmake (5.15.3+dfsg-2ubuntu0.2).
qttools5-dev (5.15.3-1).
cmake (3.22.1-1ubuntu1.22.04.1).
efivar (37-6ubuntu2).
build-essential (12.9ubuntu3).

But when I try to build, I get this error:

mou@R2D2:~/efibooteditor$ cmake --build build --config Release
[  3%] Automatic MOC and UIC for target efibooteditor
[  3%] Built target efibooteditor_autogen
[  7%] Generating efibooteditor_en.qm
Updating '/home/mou/efibooteditor/build/efibooteditor_en.qm'...
    Generated 423 translation(s) (423 finished and 0 unfinished)
[ 10%] Generating efibooteditor_it.qm
Updating '/home/mou/efibooteditor/build/efibooteditor_it.qm'...
    Generated 423 translation(s) (423 finished and 0 unfinished)
[ 14%] Generating efibooteditor_nb_NO.qm
Updating '/home/mou/efibooteditor/build/efibooteditor_nb_NO.qm'...
    Generated 423 translation(s) (20 finished and 403 unfinished)
[ 17%] Generating efibooteditor_pl.qm
Updating '/home/mou/efibooteditor/build/efibooteditor_pl.qm'...
    Generated 423 translation(s) (185 finished and 238 unfinished)
[ 21%] Generating efibooteditor_sk.qm
Updating '/home/mou/efibooteditor/build/efibooteditor_sk.qm'...
    Generated 423 translation(s) (423 finished and 0 unfinished)
[ 25%] Generating qrc_translations.cpp
[ 28%] Generating qrc_icons.cpp
[ 32%] Building CXX object CMakeFiles/efibooteditor.dir/efibooteditor_autogen/mocs_compilation.cpp.o
[ 35%] Building CXX object CMakeFiles/efibooteditor.dir/src/main.cpp.o
[ 39%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentry.cpp.o
[ 42%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentrydelegate.cpp.o
[ 46%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentryform.cpp.o
[ 50%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentrylistmodel.cpp.o
[ 53%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentrylistview.cpp.o
[ 57%] Building CXX object CMakeFiles/efibooteditor.dir/src/bootentrywidget.cpp.o
[ 60%] Building CXX object CMakeFiles/efibooteditor.dir/src/filepathdelegate.cpp.o
[ 64%] Building CXX object CMakeFiles/efibooteditor.dir/src/filepathdialog.cpp.o
[ 67%] Building CXX object CMakeFiles/efibooteditor.dir/src/devicepathview.cpp.o
[ 71%] Building CXX object CMakeFiles/efibooteditor.dir/src/devicepathproxymodel.cpp.o
[ 75%] Building CXX object CMakeFiles/efibooteditor.dir/src/driveinfo.cpp.o
[ 78%] Building CXX object CMakeFiles/efibooteditor.dir/src/efibootdata.cpp.o
[ 82%] Building CXX object CMakeFiles/efibooteditor.dir/src/efibooteditor.cpp.o
[ 85%] Building CXX object CMakeFiles/efibooteditor.dir/src/driveinfo.linux.cpp.o
[ 89%] Building C object CMakeFiles/efibooteditor.dir/src/efivar-lite.linux.c.o
[ 92%] Building CXX object CMakeFiles/efibooteditor.dir/qrc_icons.cpp.o
[ 96%] Building CXX object CMakeFiles/efibooteditor.dir/qrc_translations.cpp.o
[100%] Linking CXX executable efibooteditor
/usr/bin/ld: cannot find -lefiboot: No such file or directory
/usr/bin/ld: cannot find -lefivar: No such file or directory
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/efibooteditor.dir/build.make:448: efibooteditor] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/efibooteditor.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

**Comment by Neverous** [comment]
On ubuntu `libefiboot-dev libefivar-dev` packages need to be installed, that should fix your issue :crossed_fingers:

**Comment by Moji14** [comment]
Solved!
